# pipeline/nodes/node4_assembly.py
from typing import Dict, Any
from pipeline.state import PCOSState

def node4_assembly_fn(state: PCOSState) -> Dict[str, Any]:
    """
    Node 4: Payload Assembly and Schema Verification.
    Validates structural variables across Nodes 1, 2, and 3, ensures typing alignment,
    and initializes placeholder boundaries for Node 5 state execution.
    """
    print("\n" + "="*60)
    print("[NODE 4] EXECUTION RUN: PRODUCTION SCHEMA VERIFICATION & LOCK")
    print("="*60)

    # 1. Verification of upstream blocks to guarantee data lineage
    raw_input = state.get("raw_input", {})
    retrieved_chunks = state.get("retrieved_chunks", [])
    graph_knowledge = state.get("graph_knowledge", [])
    clinical_hypothesis = state.get("clinical_hypothesis", {})
    
    # 🌟 CRITICAL RESILIENCE GUARDRAIL: Safely catch NoneType states and normalize them
    hypotheses = state.get("hypotheses")
    if hypotheses is None:
        hypotheses = []
        
    classical_scores = state.get("classical_scores", {})
    quantum_scores = state.get("quantum_scores", {})
    ici_metrics = state.get("ici_metrics", {})
    if ici_metrics is None:
        ici_metrics = {}

    # 2. Extract keys for granular console tracking logs
    raw_input_keys = list(raw_input.keys()) if isinstance(raw_input, dict) else []
    
    # Extract hypothesis fields from whichever key the data landed in safely
    if isinstance(clinical_hypothesis, dict):
        hypothesis_keys = list(clinical_hypothesis.keys())
    elif hasattr(clinical_hypothesis, "clinical_hypothesis") and isinstance(clinical_hypothesis.clinical_hypothesis, dict):
        # Handle cases where the dictionary is double-nested from the Node 2 return mapping
        hypothesis_keys = list(clinical_hypothesis.clinical_hypothesis.keys())
    else:
        hypothesis_keys = []
        
    classical_keys = list(classical_scores.keys()) if isinstance(classical_scores, dict) else []
    quantum_keys = list(quantum_scores.keys()) if isinstance(quantum_scores, dict) else []

    # 3. Print out internal pipeline state telemetry signature trace
    print(f"[Node4 Trace] Ingested Features: {raw_input_keys}")
    print(f"[Node4 Trace] RAG Chunks Recovered: {len(retrieved_chunks)}")
    print(f"[Node4 Trace] Neo4j Path Nodes Extracted: {len(graph_knowledge)}")
    print(f"[Node4 Trace] Consensus Hypothesis Fields: {hypothesis_keys}")
    print(f"[Node4 Trace] Layer 0 Sub-Agent Hypotheses Packed: {len(hypotheses)}")
    print(f"[Node4 Trace] Classical Scores Elements: {classical_keys}")
    print(f"[Node4 Trace] Advanced Quantum Keys Detected: {quantum_keys}")
    print(f"[Node4 Trace] ICI Index Value: {ici_metrics.get('integrated_clinical_index', 'N/A')}")

    # 4. Strict structural verification safety checks
    # Verifies the presence of new metrics generated by your corrected quantum_utils.py script
    required_quantum_signals = ["quantum_interaction_score", "raw_counts", "von_neumann_entropy", "qubit_activation", "top_states"]
    missing_signals = [signal for signal in required_quantum_signals if signal not in quantum_keys]

    if missing_signals:
        print(f"⚠️ [LINEAGE WARNING] Expected quantum structural metrics missing: {missing_signals}")
    else:
        print("[SCHEMA VERIFIED] Node 1 to Node 3 payload metrics certified for mathematical XAI mapping.")

    # 5. Initialize downstream analytical state placeholders safely
    state["xai_metrics"] = {}
    state["xai_report"] = ""

    print("="*60 + "\n")

    return state